language: php

sudo: false

php:
  - 7.3
  - 7.2
  - 7.1

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then php vendor/bin/test-reporter; fi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache